// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.8.0'
//    ext.kotlin_version = '1.4.10'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10'
        classpath "io.realm:realm-gradle-plugin:5.13.1"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // hilt
//        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.28-alpha'
    }
}

allprojects {
    repositories {
        if (project.hasProperty('MAVEN_REPO')) {
            maven { url MAVEN_REPO }
        }
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.ghostscript.com/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
