
android.useAndroidX=true
android.enableJetifier=true
android.databinding.incremental=true
kapt.incremental.apt=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false

android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
org.gradle.jvmargs=-Xmx4096m

org.gradle.caching=true