apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {

    signingConfigs {
        config {
            keyAlias 'pulley_v2'
            keyPassword '<REDACTED>'
            storeFile file('./key/pulley_v2.jks')

            storePassword '<REDACTED>'
        }
    }

    compileSdkVersion 33

    defaultConfig {
        applicationId "com.freewheelin.pulley"
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 367
        versionName '1.5.16'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            renderscriptDebuggable = true
            signingConfig signingConfigs.config
        }

        debug {
            resValue("string", "PORT_NUMBER", "8089")
        }
    }

    dataBinding {
        enabled = true
    }
    viewBinding {
        enabled = true
    }

    flavorDimensions "type"

    productFlavors {
        prod {
            dimension "type"

            resValue "string", "app_name", "풀리수학"
            resValue "string", "facebook_app_id", "1045837815850615"
            resValue "string", "provider_id", "com.freewheelin.fileprovider"
        }

        beta {
            applicationIdSuffix ".beta"

            dimension "type"

            resValue "string", "app_name", "풀리수학-베타"
            resValue "string", "facebook_app_id", "3498422050272145"
            resValue "string", "provider_id", "com.freewheelin.beta.fileprovider"
        }
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    lintOptions {
//        checkReleaseBuilds false
        abortOnError false
    }
}

repositories {
    mavenCentral()
    google()
}

dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.2.0'

    // rx
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.3.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-kotlin:2.1.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin:2.1.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding-recyclerview-v7-kotlin:2.1.1'

    // retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.13'
    implementation("com.squareup.okhttp3:okhttp-urlconnection:3.12.13")
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'

    implementation 'com.github.nitrico.lastadapter:lastadapter:2.3.0'
    implementation 'com.g00fy2:versioncompare:1.3.2'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.6.0'
//    implementation 'com.google.android.material:material:1.6.0-alpha01'

    implementation 'net.danlew:android.joda:2.10.1.2'
    implementation 'com.github.bumptech.glide:glide:4.14.2'
    kapt 'com.github.bumptech.glide:compiler:4.14.2'

    implementation 'androidx.viewpager2:viewpager2:1.0.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation 'com.rm:freedrawview:1.1.2'
    implementation 'gun0912.ted:tedpermission:2.2.2'
    implementation 'com.airbnb.android:lottie:3.1.0'
//    implementation 'com.github.hyuntae0117:android-BalloonWindow:0.2.4'
    implementation 'com.github.hyuntae0117:android-RecyclerAdapters:0.6'

    implementation 'com.google.android:flexbox:2.0.1'

    // 파이어베이스
    implementation platform('com.google.firebase:firebase-bom:29.0.3')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-messaging'

    // facebook sdk
    implementation 'com.facebook.android:facebook-android-sdk:7.1.0'
    // play console
    implementation 'com.google.android.play:core:1.10.3'
    implementation 'com.google.android.play:core-ktx:1.8.1'

    implementation "androidx.core:core-ktx:1.8.0"



    // pdf
    implementation project(":pdf")

    //jsoup
    implementation 'org.jsoup:jsoup:1.13.1'

    //paging ktx
    def paging_version = "3.1.1"
    implementation "androidx.paging:paging-runtime-ktx:$paging_version"
    testImplementation "androidx.paging:paging-common-ktx:$paging_version"
    implementation "androidx.paging:paging-rxjava2-ktx:$paging_version"

    // lifecycle
    def lifecycle_version = "2.5.1"
    def lifecycle_extension_version = "2.2.0"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_extension_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

    // fragment
    def fragment_version = "1.5.5"
    // Kotlin
    implementation "androidx.fragment:fragment-ktx:$fragment_version"

    // exoplayer
    implementation 'com.google.android.exoplayer:exoplayer-core:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.18.2'

    kapt 'com.android.databinding:compiler:3.1.4'

    def roomVersion = "2.5.0"
    def roomKaptVersion = "2.4.3"
    implementation "androidx.room:room-runtime:$roomVersion"
    implementation "androidx.room:room-ktx:$roomVersion"
    kapt "androidx.room:room-compiler:$roomVersion"

    // 사용하던 custom view는 남아있으나 webview로 변경하여서 추후 삭제해야할것같음
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.0.1'

    implementation 'io.channel:plugin-android:10.0.7'
    implementation 'io.channel:plugin-android-fcm:10.0.7'

    // lesson pagecall
    // host 처리 문제로 사용안함
    // implementation 'com.github.pplink.pagecall-android-sdk:sdk:0.0.3'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
    testImplementation 'org.mockito:mockito-core:3.9.0'
    testImplementation 'androidx.test:core:1.5.0'
    testImplementation "org.robolectric:robolectric:4.1"
    testImplementation 'joda-time:joda-time:2.10.1'
    testImplementation 'org.mockito:mockito-inline:2.13.0'

    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.1'

    debugImplementation 'com.amitshekhar.android:debug-db:1.0.6'
}

